### ISSUE TITLE
Invalid Regex

### ISSUE THREAD

**Issue by PromoFaux** [CipherOps/PiHoleREGEX#1]
Hey just a quick ref - these are invalid Regex for Pi-hole, they'll never match anything as they are URLs not domains

https://github.com/CipherOps/PiHoleBlocklists/blob/fc9c6efa6b15c832313ea6ca1e1fdda425df9f1b/REGEX.txt#L18-L48

Also in the readme:

> from there you have to manually copy and paste each item

You can actually just copy paste the whole list into text box and it will add them:

![image](https://user-images.githubusercontent.com/1998970/130670985-8a5d46e7-b756-41a9-8851-2bac10cb4f8b.png) (there are also apparently 2 dupes ;))

**Comment by CipherOps** [comment]
Fixed, thanks PromoFaux.

Leaving this open in case the README is still wrong on how to add the REGEX.
